version: 2
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml.dist"
exclude_patterns:
  - web/themes/custom/vibe/assets/
  - web/themes/custom/vibe/css/
  - web/themes/custom/vibe/js/
