language: php
php:
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate

install:
  - composer install --ignore-platform-reqs --no-suggest
  - export COMPOSER_BIN_DIR=$TRAVIS_BUILD_DIR/vendor/bin
  - export PATH=$COMPOSER_BIN_DIR:$PATH
  - npm install -g snyk

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
  - snyk test
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml web/modules/custom

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
  - codacycoverage clover
  - php-coveralls
  - bash <(curl -s https://codecov.io/bash)
  - snyk monitor

cache:
  directories:
    - $HOME/.composer/cache
    - $(npm config get prefix)/lib/node_modules
